spring.application.name=marketplace
spring.datasource.url=jdbc:mysql://localhost:3306/marketplace?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
application.security.jwt.secretKey=una-clave-secreta-de-al-menos-32-caracteres
application.security.jwt.expiration=86400000